# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/lorenzwalthert/pre-commit-hooks
    rev: v0.3.2.9021
    hooks:
    -   id: style-files
    -   id: parsable-R
    -   id: lintr
